import configparser
import json

config = configparser.ConfigParser()
config.read("./config.cfg")

TRAIN_DATASET_DIR = str(config["DATASET"]["TRAIN_DATASET_DIR"])
VAL_DATASET_DIR = str(config["DATASET"]["VAL_DATASET_DIR"])
PRETRAINEDWEIGHT_DIR = str(config["DATASET"]["PRETRAINEDWEIGHT_DIR"])

MAX_PATCHES_INPUT = int(config["HYPER_PARAMETERS"]["MAX_PATCHES"])
MAX_LENGTH_INPUT = int(config["HYPER_PARAMETERS"]["MAX_LENGTH"])
PADDINNG_INPUT = str(config["HYPER_PARAMETERS"]["PADDINNG"])
TRUNCATION_INPUT = config.getboolean('HYPER_PARAMETERS', 'TRUNCATION') 
IS_VQA_INPUT = config.getboolean('HYPER_PARAMETERS', 'IS_VQA')
ADD_SPECIAL_TOKENS = config.getboolean('HYPER_PARAMETERS', 'ADD_SPECIAL_TOKENS')

TOTAL_EPOCHES = int(config["HYPER_PARAMETERS"]["TOTAL_EPOCHES"])
TRAIN_BATCH_SIZE = int(config["HYPER_PARAMETERS"]["TRAIN_BATCH_SIZE"])
VAL_BATCH_SIZE = int(config["HYPER_PARAMETERS"]["VAL_BATCH_SIZE"])
LR = float(config["HYPER_PARAMETERS"]["LR"])
WARM_UP_STEPS = int(config["HYPER_PARAMETERS"]["WARM_UP_STEPS"])


ENABLE_OPTMIZATION = config.getboolean('OPTIMIZATION', 'ENABLE_OPTMIZATION')
R_VALUE = int(config["OPTIMIZATION"]["R_VALUE"])
ALPHA_VALUE = int(config["OPTIMIZATION"]["ALPHA_VALUE"])
DROPOUT = float(config["OPTIMIZATION"]["DROPOUT"])

SAVE_MODEL_DIR = str(config["OUTPUT_DIR"]["SAVE_MODEL_DIR"])
